# Generated by Django 5.0.1 on 2024-01-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_tokens_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_time',
        ),
    ]
