# Generated by Django 5.0.1 on 2024-01-21 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_message_sent_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
