# Generated by Django 5.0.1 on 2024-01-21 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_message_sent_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='sent_time',
        ),
    ]
